
services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass123

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: